config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :reservations
  resources :rooms do
    collection do
      get 'search'
    end
  end
  
  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
    post '/users/sign_in' => 'devise/sessions#create'
    get '/users/account' => 'devise/registrations#show'
  end

  resources :users, only: [:show, :edit, :update]
  root 'home#index'
  get 'home/index'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

    validates :title, presence: true
    validates :about, presence: true
    validates :price, presence: true,numericality:{only_integer: true, greater_than_or_equal_to: 1}
    validates :adress, presence: true
    
    has_many :reservations
    belongs_to :user, optional: true

    mount_uploader :img,ImgUploader
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only:[:index, :search]
  before_action :authenticate_user,{only:[:create,:edit,:update]}
  def index
    @rooms=Room.where(user_id: current_user).includes(:user).order("created_at DESC")
    @user=current_user
  end

  def new
    @room=Room.new
  end

  def create
    @room=Room.new(**room_params,user_id: current_user.id)
    if @room.save
      flash[:notice]="情報を登録しました"
      redirect_to :rooms
    else
      render "new"
    end
  end

  def show
    @user=current_user
    @room=Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room=Room.find(params[:id])
  end

  def update
    @room=Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice]="情報を編集しました"
      redirect_to :rooms
    else
      render "edit"
    end
  end

  def destroy
    @room=Room.find(params[:id])
    @room.destroy
    redirect_to :rooms
  end

  def search
    @results =@q.result
    @user=current_user
  end



  private

  def set_q
    @q=Room.ransack(params[:q])

  end
  def room_params
    params.require(:room).permit(:title,:about,:price,:adress,:img)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="FormWrapper">
 <section class="FormContainer">
  <h2>編集</h2>
  
  <%=form_with model:@room do |f|%>
  <%= render "shared/error", obj: f.object %>
   <table>
    <tr>
     <th><%=f.label :title,"施設名"%></th>
     <td><%=f.text_field :title%></td>
    </tr>

    <tr>
     <th><%=f.label :about,"施設詳細"%></th>
     <td><%=f.text_area :about%></td>
    </tr>

    <tr>
     <th><%=f.label :price,"料金"%></th>
     <td><%=f.text_field :price%></td>
    </tr>

    <tr>
     <th><%=f.label :adress,"住所"%></th>
     <td><%=f.text_field :adress%></td>
    </tr>

    <tr>
     <th><%= f.label :img,"画像"%></th>
     <td><%= f.file_field :img%></td>
    </tr>
   </table>

   <div>
    <ul>
     <li><%=f.submit"保存"%></li>
     <li><%=link_to "キャンセル",:rooms %></li>
    </ul>
   </div>
  <%end%>
 </section>
</div>

app/views/rooms/index.html.erb
<section class="container OwnerRoomsContainer">
 <h2>登録済み施設一覧</h2>
 <div class="table-responsive">

  <% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
 <% end %>
 
  <table class="table">
   <thead>
    <tr>
     <th>画像</th>
     <th>施設名</th>
     <th>紹介文</th>
     <th>料金</th>
     <th>住所</th>
     <th>作成日</th>
     <th></th>
    </tr>
   </thead>
   <tbody>
    <% @rooms.each do |room|%>
     <tr>
      <td><%=image_tag room.img_url,size: "200x150"%></td>
      <td><%=link_to"#{room.title}",{controller: 'rooms', action: 'show', id: room.id}%></td>
      <td><%=room.about%></td>
      <td><%=room.price%></td>
      <td><%=room.adress%></td>
      <td><%=room.created_at&.strftime("%Y/%m/%d")%></td>
     </tr>
    <% end %>
   </tbody>
  </table>
 </div>
</section>

app/views/rooms/new.html.erb
<div class="FormWrapper">
 <section class="FormContainer">
  <h2>新規登録</h2>
  <%=form_with model:@room do |f|%>
  <%= render "shared/error", obj: f.object %>
   <table>
    <tr>
     <th><%=f.label :title,"施設名"%></th>
     <td><%=f.text_field :title%></td>
    </tr>

    <tr>
     <th><%=f.label :about,"施設詳細"%></th>
     <td><%=f.text_area :about%></td>
    </tr>

    <tr>
     <th><%=f.label :price,"料金"%></th>
     <td><%=f.text_field :price%></td>
    </tr>

    <tr>
     <th><%=f.label :adress,"住所"%></th>
     <td><%=f.text_field :adress%></td>
    </tr>

    <tr>
     <th><%=f.label :img,"画像"%></th>
     <td><%=f.file_field :img%></td>
    </tr>
   </table>
   <%=f.hidden_field :user_id, value:current_user%>

   <div>
    <ul>
     <li><%=f.submit"保存"%></li>
     <li><%=link_to "キャンセル",:rooms %></li>
    </ul>
   </div>
  <%end%>
 </section>
</div>

app/views/rooms/search.html.erb
  <div class="SearchRooms_FormContainer">
   <%= search_form_for @q, url: search_rooms_path do |f|%>
    <div class="Search_Field">
    <%= f.search_field :adress_cont, placeholder:"エリアを入力"%>
    <%= f.search_field :title_or_about_cont, placeholder:"キーワードを入力"%>
    </div>
    <br>
    <div class="SearchRooms_button">
     <%=f.submit "検索"%>
    </div>
  <%end%>
  </div>

  <div class="container RoomsContainer">
   <p class="RoomsContainer_result">
   <h2>検索結果: <%= @results.count(:id)%>件見つかりました</h2>
   </p>

   <ul class="table-responsive">
   <% @results.each do |r|%>
    <li class="Room">
     <% if r.img%>
      <%=image_tag r.img.url, size:"120x70"%>
     <%else%>
      <img src="https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png" class="room_image" alt="デフォルト">
     <%end%>
     <div class="RoomWrapper">
     <p class="Room_Name"><%=r.title%></p>
     <p class="Room_Adress"><%=r.adress%></p>
     <p class="Room_About"><%=r.about%></p>
     <div class="Room_Footer">
      <p class="Room_Price">¥<%=r.price%></p>
      <%=link_to "詳細はこちら", room_path(r) %>
     </div>
     <%end%>
     </div> 
    </li>
   </ul>
  </div>

app/views/rooms/show.html.erb
<section class="ShowContainer">
 <div class="container">
  <h3>施設詳細<h3>
  <%if user_signed_in? && @room.user_id == current_user.id%>
   <%= link_to"編集",edit_room_path(@room.id)%>
   <%= link_to"削除",@room, method: :delete%>
   
  <%end%>

  <table>
   <tr>
    <td><%=image_tag @room.img.url,size:"700x500"%></td>
   </tr>
   <tr>
    <td>施設名：<%=@room.title%></td>
   </tr>
   <tr>
    <td>住所：<%=@room.adress%></td>
   </tr>
   <tr>
    <td>施設紹介：<%=@room.about%></td>
   </tr>
   <tr>
    <td>料金(/泊)：¥<%=@room.price%></td>
   </tr>
  </table>
<%if user_signed_in?%>
 <%=form_with model:@reservation,method: :get,url:new_reservation_path do |f|%>
 <br>
 <%= render "shared/error", obj: f.object %>
 <br>
  <%=f.hidden_field :room_id, value:@room.id%>
  <%=f.hidden_field :user_id, value:current_user.id%>
  <%=f.hidden_field :total_price, value:@room.price%>
  <%=f.hidden_field :title, value:@room.title%>
  <%=f.hidden_field :img, value:@room.img%>
  <%=f.hidden_field :about, value:@room.about%>

  <label>チェックイン</label>
   <%=f.date_field :start_date%>
   <br>
  <label>チェックアウト</label>
   <%=f.date_field :end_date%>
   <br>
  <label>人数</label>
   <%=f.text_field :people%>
   <br>
  <%=f.submit "この日程で予約する"%>
 <%end%>
<%else%>
  <%=link_to"ログインして予約する",new_user_session_path%>
<%end%>
<br>
  <ul>
   <li><%=link_to"戻る",:rooms%></li>
  </ul>
 </div>
</section>